[package]
name = "app_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
repose-ui = { path = "../../../repose/crates/repose-ui" }
repose-core = { path = "../../../repose/crates/repose-core" }
domain = { path = "../domain" }
crossbeam-channel = "0.5.15"
