[workspace]
members = [
  "crates/domain",
  "crates/backend_pacman",
  "crates/backend_aur",
  "crates/app_ui",
  "crates/app_shell",
]
resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
