[package]
name = "backend_aur"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
ureq = { version = "3", features = ["json"] }
serde = { version = "1", features = ["derive"] }
urlencoding = "2"
tempfile = "3"
